SET_COLLABORATOR_ROLE_AS_MANDATORY = "SET PERSIST mandatory_roles = 'collaborator';"
DB_CONF_SET_AUTO_ROLE_ON_LOGIN = "SET PERSIST activate_all_roles_on_login = ON;"

CREATE_QUERY_LIST = [SET_COLLABORATOR_ROLE_AS_MANDATORY, DB_CONF_SET_AUTO_ROLE_ON_LOGIN]
