ADD_PRIVILEGES_COLLABORATOR_ROLE = "GRANT SELECT ON epicevent.* TO 'collaborator'"
ADD_PRIVILEGES_COMMERCIAL_ROLE = (
    "GRANT INSERT, UPDATE ON epicevent.client TO 'commercial'"
)
ADD_PRIVILEGES_COMMERCIAL_ROLE_2 = (
    "GRANT INSERT, UPDATE ON epicevent.contract TO 'commercial'"
)
ADD_PRIVILEGES_COMMERCIAL_ROLE_3 = "GRANT INSERT ON epicevent.event TO 'commercial'"

ADD_PRIVILEGES_GESTION_ROLE_1 = (
    "GRANT INSERT,UPDATE ON epicevent.collaborator TO 'gestion';"
)

ADD_PRIVILEGES_GESTION_ROLE_2 = (
    "GRANT INSERT,UPDATE ON epicevent.contract TO 'gestion';"
)

ADD_PRIVILEGES_GESTION_ROLE_3 = (
    "GRANT UPDATE (support_contact) ON epicevent.event TO 'gestion';"
)

ADD_PRIVILEGES_GESTION_ROLE_4 = "GRANT CREATE USER ON *.* TO 'gestion';"

ADD_PRIVILEGES_GESTION_ROLE_5 = (
    "GRANT ALL PRIVILEGES ON *.* TO 'gestion' WITH GRANT OPTION;"
)

CREATE_QUERY_LIST = [
    ADD_PRIVILEGES_COLLABORATOR_ROLE,
    ADD_PRIVILEGES_COMMERCIAL_ROLE,
    ADD_PRIVILEGES_COMMERCIAL_ROLE_2,
    ADD_PRIVILEGES_GESTION_ROLE_1,
    ADD_PRIVILEGES_GESTION_ROLE_2,
    ADD_PRIVILEGES_GESTION_ROLE_3,
    ADD_PRIVILEGES_GESTION_ROLE_4,
    ADD_PRIVILEGES_GESTION_ROLE_5,
]
