from mysql.connector import Error

ADD_PRIVILEGES_COLLABORATOR_ROLE = "GRANT SELECT ON epicevent.* TO 'collaborator'"

ADD_PRIVILEGE_SUPPORT_ROLE_1 = "GRANT UPDATE ON epicevent.event TO 'support'"

ADD_PRIVILEGES_COMMERCIAL_ROLE = (
    "GRANT INSERT, UPDATE ON epicevent.client TO 'commercial'"
)
ADD_PRIVILEGES_COMMERCIAL_ROLE_2 = (
    "GRANT INSERT, UPDATE ON epicevent.contract TO 'commercial'"
)
ADD_PRIVILEGES_COMMERCIAL_ROLE_3 = "GRANT INSERT ON epicevent.event TO 'commercial'"

ADD_PRIVILEGES_GESTION_ROLE_1 = (
    "GRANT INSERT,UPDATE ON epicevent.collaborator TO 'gestion';"
)

ADD_PRIVILEGES_GESTION_ROLE_2 = (
    "GRANT INSERT,UPDATE ON epicevent.contract TO 'gestion';"
)

ADD_PRIVILEGES_GESTION_ROLE_3 = (
    "GRANT UPDATE (support_contact, last_update) ON epicevent.event TO 'gestion';"
)

ADD_PRIVILEGES_GESTION_ROLE_4 = "GRANT CREATE USER ON *.* TO 'gestion';"

ADD_PRIVILEGES_GESTION_ROLE_5 = (
    "GRANT EXECUTE ON PROCEDURE AssignRoleToCollaborator TO 'gestion';"
)

ADD_PRIVILEGE_QUERY_LIST = [
    ADD_PRIVILEGES_COLLABORATOR_ROLE,
    ADD_PRIVILEGE_SUPPORT_ROLE_1,
    ADD_PRIVILEGES_COMMERCIAL_ROLE,
    ADD_PRIVILEGES_COMMERCIAL_ROLE_2,
    ADD_PRIVILEGES_COMMERCIAL_ROLE_3,
    ADD_PRIVILEGES_GESTION_ROLE_1,
    ADD_PRIVILEGES_GESTION_ROLE_2,
    ADD_PRIVILEGES_GESTION_ROLE_3,
    ADD_PRIVILEGES_GESTION_ROLE_4,
    ADD_PRIVILEGES_GESTION_ROLE_5,
]

REVOKE_PRIVILEGES_COLLABORATOR_ROLE = "REVOKE SELECT ON epicevent.* FROM 'collaborator'"
REVOKE_PRIVILEGES_SUPPORT_ROLE = "REVOKE UPDATE ON epicevent.event FROM 'support'"
REVOKE_PRIVILEGES_COMMERCIAL_ROLE = (
    "REVOKE INSERT, UPDATE ON epicevent.client FROM 'commercial'"
)
REVOKE_PRIVILEGES_COMMERCIAL_ROLE_2 = (
    "REVOKE INSERT, UPDATE ON epicevent.contract FROM 'commercial'"
)
REVOKE_PRIVILEGES_COMMERCIAL_ROLE_3 = (
    "REVOKE INSERT ON epicevent.event FROM 'commercial'"
)

REVOKE_PRIVILEGES_GESTION_ROLE_1 = (
    "REVOKE INSERT, UPDATE ON epicevent.collaborator FROM 'gestion'"
)
REVOKE_PRIVILEGES_GESTION_ROLE_2 = (
    "REVOKE INSERT, UPDATE ON epicevent.contract FROM 'gestion'"
)
REVOKE_PRIVILEGES_GESTION_ROLE_3 = (
    "REVOKE UPDATE (support_contact) ON epicevent.event FROM 'gestion'"
)
REVOKE_PRIVILEGES_GESTION_ROLE_4 = "REVOKE CREATE USER ON *.* FROM 'gestion'"

REVOKE_PRIVILEGES_GESTION_ROLE_5 = (
    "REVOKE EXECUTE ON PROCEDURE AssignRoleToCollaborator FROM 'gestion'"
)

REVOKE_PRIVILEGE_QUERY_LIST = [
    REVOKE_PRIVILEGES_COLLABORATOR_ROLE,
    REVOKE_PRIVILEGES_SUPPORT_ROLE,
    REVOKE_PRIVILEGES_COMMERCIAL_ROLE,
    REVOKE_PRIVILEGES_COMMERCIAL_ROLE_2,
    REVOKE_PRIVILEGES_COMMERCIAL_ROLE_3,
    REVOKE_PRIVILEGES_GESTION_ROLE_1,
    REVOKE_PRIVILEGES_GESTION_ROLE_2,
    REVOKE_PRIVILEGES_GESTION_ROLE_3,
    REVOKE_PRIVILEGES_GESTION_ROLE_4,
    REVOKE_PRIVILEGES_GESTION_ROLE_5,
]
