from mysql.connector import Error

CREATE_ROLE_COLLABORATOR = "CREATE ROLE 'collaborator'"
CREATE_ROLE_COMMERCIAL = "CREATE ROLE 'commercial'"
CREATE_ROLE_SUPPORT = "CREATE ROLE 'support'"
CREATE_ROLE_GESTION = "CREATE ROLE 'gestion'"

DROP_ROLE_COLLABORATOR = "DROP ROLE IF EXISTS 'collaborator'"
DROP_ROLE_COMMERCIAL = "DROP ROLE IF EXISTS 'commercial'"
DROP_ROLE_SUPPORT = "DROP ROLE IF EXISTS 'support'"
DROP_ROLE_GESTION = "DROP ROLE IF EXISTS 'gestion'"

CREATE_ROLE_QUERY_LIST = [
    CREATE_ROLE_COLLABORATOR,
    CREATE_ROLE_GESTION,
    CREATE_ROLE_COMMERCIAL,
    CREATE_ROLE_SUPPORT,
]
DROP_ROLE_QUERY_LIST = [
    DROP_ROLE_COLLABORATOR,
    DROP_ROLE_GESTION,
    DROP_ROLE_COMMERCIAL,
    DROP_ROLE_SUPPORT,
]


