AUTO_ASSIGN_COMMERCIAL_TO_CLIENT = """
CREATE TRIGGER auto_assign_commercial_to_client BEFORE INSERT ON client
FOR EACH ROW 
SET new.collaborator_id = get_collaborator_id();
"""

DROP_ASSIGN_COMMERCIAL_TO_CLIENT = "DROP TRIGGER IF EXISTS auto_assign_commercial_to_client"

CREATE_TRIGGER_QUERY_LIST = [AUTO_ASSIGN_COMMERCIAL_TO_CLIENT]
DROP_TRIGGER_QUERY_LIST = [DROP_ASSIGN_COMMERCIAL_TO_CLIENT]